[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'repo', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 402
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  Hoi 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'repo', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'repo', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] name 'os' is not defined
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/ExonRobot/Exon/modules/info.py", line 114, in info_func
    os.remove(photo)
NameError: name 'os' is not defined
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Unhandled exception on quott_
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/quote.py", line 364, in quott_
    if not event.client._bot:
AttributeError: 'TelegramClient' object has no attribute '_bot'
[ᴇxᴏɴ] Unhandled exception on quott_
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/quote.py", line 364, in quott_
    if not event.client._bot:
AttributeError: 'TelegramClient' object has no attribute '_bot'
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] 'utf-16-le' codec can't decode bytes in position 10-11: unexpected end of data
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/ExonRobot/Exon/modules/watcher.py", line 57, in chat_watcher_func
    if entity.type == MessageEntityType.BOT_COMMAND and message_text[: 0 + entity.length].lower() in possible:
  File "/root/fallen/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 56, in __getitem__
    return parser_utils.remove_surrogates(parser_utils.add_surrogates(self)[item])
  File "/root/fallen/lib/python3.8/site-packages/pyrogram/parser/utils.py", line 37, in remove_surrogates
    return text.encode("utf-16", "surrogatepass").decode("utf-16")
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 10-11: unexpected end of data
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 419
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-15_01-00-00/db_LuffyRoxbot_2024-06-15_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/ExonRobot/Exon/modules/watcher.py", line 51, in chat_watcher_func
    userid = message.from_user.id
AttributeError: 'NoneType' object has no attribute 'id'
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-16_01-00-00/db_LuffyRoxbot_2024-06-16_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Unhandled exception on lastname
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/ubot.py", line 57, in lastname
    async with ubot.conversation(chat) as conv:
AttributeError: 'NoneType' object has no attribute 'conversation'
[ᴇxᴏɴ] Unhandled exception on lastname
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/ubot.py", line 57, in lastname
    async with ubot.conversation(chat) as conv:
AttributeError: 'NoneType' object has no attribute 'conversation'
[ᴇxᴏɴ] Unhandled exception on lastname
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/client/updates.py", line 543, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/ubot.py", line 57, in lastname
    async with ubot.conversation(chat) as conv:
AttributeError: 'NoneType' object has no attribute 'conversation'
[ᴇxᴏɴ] Flood control exceeded. Retry in 5.0 seconds
[ᴇxᴏɴ] Error while getting Updates: Bad Gateway
[ᴇxᴏɴ] Error while getting Updates: Bad Gateway
[ᴇxᴏɴ] Error while getting Updates: Bad Gateway
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-17_01-00-00/db_LuffyRoxbot_2024-06-17_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Bhai%20ek%20kaam%20kar%20de "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=hi&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Bhai%20ek%20kaam%20kar%20de "HTTP/1.1 200 OK"
[ᴇxᴏɴ] Flood control exceeded. Retry in 5.0 seconds
[ᴇxᴏɴ] Error while getting Updates: Bad Gateway
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-18_01-00-01/db_LuffyRoxbot_2024-06-18_01-00-01.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-19_01-00-00/db_LuffyRoxbot_2024-06-19_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=So%20kaha%20se%20ho%20aap%20%3F "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=hi&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=So%20kaha%20se%20ho%20aap%20%3F "HTTP/1.1 200 OK"
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-20_01-00-00/db_LuffyRoxbot_2024-06-20_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] 'ChatMember' object has no attribute 'can_post_messages'
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/ExonRobot/Exon/modules/pin.py", line 264, in anti_channel_pin
    permissions = await member_permissions(chat_id, user_id)
  File "/root/ExonRobot/Exon/utils/pluginhelp.py", line 349, in member_permissions
    if member.can_post_messages:
AttributeError: 'ChatMember' object has no attribute 'can_post_messages'
[ᴇxᴏɴ] {'update_id': 447340868, 'message': {'reply_to_message': {'chat': {'type': 'supergroup', 'username': 'Anime_Chat_Group_Catalogue', 'title': 'Anime Chat Group Catalogue', 'id': -1002102415483}, 'group_chat_created': False, 'delete_chat_photo': False, 'channel_chat_created': False, 'entities': [], 'photo': [], 'new_chat_photo': [], 'message_id': 233727, 'caption_entities': [], 'new_chat_members': [], 'date': 1718876985, 'supergroup_chat_created': False, 'text': 'O₹ ka investment kon mere sath kaam karega personal message karo', 'from': {'is_bot': False, 'username': 'Q966227', 'id': 6482372661, 'first_name': 'Amit'}}, 'chat': {'type': 'supergroup', 'username': 'Anime_Chat_Group_Catalogue', 'title': 'Anime Chat Group Catalogue', 'id': -1002102415483}, 'group_chat_created': False, 'message_thread_id': 233727, 'delete_chat_photo': False, 'channel_chat_created': False, 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'photo': [], 'new_chat_photo': [], 'message_id': 233733, 'caption_entities': [], 'new_chat_members': [], 'date': 1718877029, 'supergroup_chat_created': False, 'text': '/tmute 10m', 'from': {'is_bot': False, 'username': 'daisukkiee', 'id': 6653725844, 'language_code': 'en', 'first_name': 'I S Λ G I'}}}
[ᴇxᴏɴ] ERROR muting user 6482372661 in chat Anime Chat Group Catalogue (-1002102415483) due to Can't parse entities: unexpected end of name token at byte offset 31
Traceback (most recent call last):
  File "/root/ExonRobot/Exon/modules/muting.py", line 284, in temp_mute
    bot.sendMessage(
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 534, in send_message
    return self._message(  # type: ignore[return-value]
  File "/root/fallen/lib/python3.8/site-packages/telegram/ext/extbot.py", line 203, in _message
    result = super()._message(
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/root/fallen/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/root/fallen/lib/python3.8/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: unexpected end of name token at byte offset 31
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] Unhandled error while receiving data
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 505, in _recv_loop
    body = await self._connection.recv()
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 301, in recv
    raise err
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
[ᴇxᴏɴ] Unhandled error while receiving data
Traceback (most recent call last):
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 505, in _recv_loop
    body = await self._connection.recv()
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 301, in recv
    raise err
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/root/fallen/lib/python3.8/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] socket.send() raised exception.
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-21_01-00-00/db_LuffyRoxbot_2024-06-21_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] {'update_id': 447349905, 'message': {'reply_to_message': {'chat': {'type': 'supergroup', 'username': 'Anime_Chat_Group_Catalogue', 'title': 'Anime Chat Group Catalogue', 'id': -1002102415483}, 'group_chat_created': False, 'message_thread_id': 237513, 'delete_chat_photo': False, 'channel_chat_created': False, 'entities': [{'type': 'url', 'offset': 127, 'length': 53}, {'type': 'url', 'offset': 303, 'length': 53}], 'photo': [], 'new_chat_photo': [], 'message_id': 238512, 'caption_entities': [], 'new_chat_members': [], 'date': 1718989902, 'supergroup_chat_created': False, 'text': 'Awesome game from TeenPatti Gold \nDaily winnings up to ₹ 7 Lakhs\n100% fair & \nsecure Cash game! \n Install and got bonus + ₹10\n\nhttps://refer9.com/gold/g6918l?f=w&p=default&tp=gold2\n\n से बहुत बढ़िया गेम \nप्रतिदिन 7 लाख तक जीत सकते है \n100% निष्पक्ष और सुरक्षित कैश गेम!\nInstall करे और ₹ 10 का बोनस पाएँ\n\nhttps://refer9.com/gold/g6918l?f=w&p=default&tp=gold2', 'from': {'is_bot': False, 'id': 853017872, 'first_name': 'Ryzen'}}, 'chat': {'type': 'supergroup', 'username': 'Anime_Chat_Group_Catalogue', 'title': 'Anime Chat Group Catalogue', 'id': -1002102415483}, 'group_chat_created': False, 'message_thread_id': 237513, 'delete_chat_photo': False, 'channel_chat_created': False, 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'photo': [], 'new_chat_photo': [], 'message_id': 238515, 'caption_entities': [], 'new_chat_members': [], 'date': 1718989924, 'supergroup_chat_created': False, 'text': '/tmute 10m', 'from': {'is_bot': False, 'username': 'Riyoshie', 'id': 6653725844, 'language_code': 'en', 'first_name': 'I S Λ G I'}}}
[ᴇxᴏɴ] ERROR muting user 853017872 in chat Anime Chat Group Catalogue (-1002102415483) due to Can't parse entities: unexpected end of name token at byte offset 31
Traceback (most recent call last):
  File "/root/ExonRobot/Exon/modules/muting.py", line 284, in temp_mute
    bot.sendMessage(
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 534, in send_message
    return self._message(  # type: ignore[return-value]
  File "/root/fallen/lib/python3.8/site-packages/telegram/ext/extbot.py", line 203, in _message
    result = super()._message(
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/root/fallen/lib/python3.8/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/root/fallen/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/root/fallen/lib/python3.8/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: unexpected end of name token at byte offset 31
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-22_01-00-00/db_LuffyRoxbot_2024-06-22_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-23_01-00-00/db_LuffyRoxbot_2024-06-23_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7fbb09560a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781619917fa3838de01d07, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781619917fa3838de01d07"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f7955b60a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 667816fc42168d7c8a35de70, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "667816fc42168d7c8a35de70"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f2f5c860a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781797f665c4ae19134d64, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781797f665c4ae19134d64"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f2b74368a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781906a0462e6c5993bf3c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781906a0462e6c5993bf3c"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f8a3d294a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781967fb731160750dd90b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781967fb731160750dd90b"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f64bf910a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 667819f23d9b1d5820362a68, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "667819f23d9b1d5820362a68"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f03b2bb0a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781a2865535ad033b9e210, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781a2865535ad033b9e210"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f79f6a78a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781a96e7fb5c78da63e4b5, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781a96e7fb5c78da63e4b5"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f650f3d8a60>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781ac6896ede9d5fd906ea, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781ac6896ede9d5fd906ea"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 425
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66781ac6896ede9d5fd906e9, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781ac6896ede9d5fd906e9"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] Received signal 2 (SIGINT), stopping...
[ᴇxᴏɴ] Exiting immediately!
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f6ea2cf9fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781bd10da6b22e166d6927, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781bd10da6b22e166d6927"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f8cc934dfc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781bf5909de26a4b8083aa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781bf5909de26a4b8083aa"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f03113a1fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c113e7f2851178bf584, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781c113e7f2851178bf584"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7f1ebc139fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c2ceb31a603c5b5eabc, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781c2ceb31a603c5b5eabc"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ᴇxᴏɴ ɪs sᴛᴀʀᴛɪɴɢ. | ᴀɴ ᴀʙɪsʜɴᴏɪᴍғ ᴘʀᴏᴊᴇᴄᴛ ᴘᴀʀᴛs. | ʟɪᴄᴇɴsᴇᴅ ᴜɴᴅᴇʀ ɢᴘʟᴠ3.
[ᴇxᴏɴ] 𝐒𝐩𝐚𝐦𝐖𝐚𝐭𝐜𝐡 ᴀᴘɪ ᴋᴇʏ ɪs ᴍɪssɪɴɢ! ʀᴇᴄʜᴇᴄᴋ ʏᴏᴜʀ ᴄᴏɴғɪɢ.
[ᴇxᴏɴ] [PostgreSQL] Connecting to database......
[ᴇxᴏɴ] [PostgreSQL] Connection successful, session started.
[ᴇxᴏɴ] ɴᴏᴛᴇ: ᴀɴᴛɪsᴘᴀᴍ ʟᴏᴀᴅᴇᴅ!
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] [ᴇxᴏɴ] →  sᴜᴄᴄᴇssғᴜʟʟʏ ʟᴏᴀᴅᴇᴅ ᴍᴏᴅᴜʟᴇs: ['afk', 'wallpaper', 'connection', 'error_handling', 'rules', 'cleaner', 'userinfo', 'cust_filters', 'info', 'pin', 'dev', 'quote', 'purge', 'antichannel', 'karmas', 'eval', 'disasters', 'backups', 'disable', 'remote_cmds', 'blacklist_stickers', 'shell', 'welcome', 'admin', 'reporting', 'muting', 'gtranslator', 'disable_help', 'Callback', 'locks', 'dbcleanup', 'ping', 'log_channel', 'cron_jobs', 'blacklist', 'users', 'forcesub', 'language', 'stickers', 'notes', 'feds', 'fonts', 'modules', 'feedback', 'global_bans', 'blacklistusers', 'truth_and_dare', 'uall', 'watcher', 'tags', 'zombies', 'antiflood', 'bans', 'tools', 'approval', 'invitelinks', 'stats', 'antiraid', 'nightmode', 'debug', 'couples', 'ubot', 'webss', 'warns', 'misc', 'weather']
[ᴇxᴏɴ] Can't parse entities: can't find end of the entity starting at byte offset 425
[ᴇxᴏɴ] ᴜsɪɴɢ ʟᴏɴɢ ᴘᴏʟʟɪɴɢ. ........... ᴇɴᴊᴏʏ ʏᴏᴜʀ ʙᴏᴛ sᴛᴀʀᴛᴇᴅ ᴀs →  𝐋𝐔𝐅𝐅𝐘 
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d81, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66781c4c4692490b22d69d81"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 400, in _pooled
    self.dispatch_error(promise.update, promise.exception, promise=promise)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 400, in _pooled
    self.dispatch_error(promise.update, promise.exception, promise=promise)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-24_01-00-00/db_LuffyRoxbot_2024-06-24_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Unhandled exception on handler
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 867, in handler
    meme = await drawText(file, text)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 900, in drawText
    u_width, u_height = draw.textsize(u_text, font=m_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
[ᴇxᴏɴ] Unhandled exception on handler
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 867, in handler
    meme = await drawText(file, text)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 900, in drawText
    u_width, u_height = draw.textsize(u_text, font=m_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
[ᴇxᴏɴ] Unhandled exception on handler
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 867, in handler
    meme = await drawText(file, text)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 900, in drawText
    u_width, u_height = draw.textsize(u_text, font=m_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/root/ExonRobot/Exon/modules/helper_funcs/handlers.py", line 128, in handle_update
    return self.callback(update, context)
  File "/root/ExonRobot/Exon/modules/helper_funcs/chat_status.py", line 521, in connected_status
    return func(update, context, *args, **kwargs)
  File "/root/ExonRobot/Exon/modules/helper_funcs/chat_status.py", line 383, in is_admin
    return func(update, context, *args, **kwargs)
  File "/root/ExonRobot/Exon/modules/helper_funcs/chat_status.py", line 468, in restrict_rights
    return func(update, context, *args, **kwargs)
  File "/root/ExonRobot/Exon/modules/helper_funcs/anonymous.py", line 97, in awrapper
    return func(update, context, *args, **kwargs)
  File "/root/ExonRobot/Exon/modules/log_channel.py", line 63, in log_action
    result = func(update, context, *args, **kwargs)
  File "/root/ExonRobot/Exon/modules/bans.py", line 111, in ban
    message.reply_text("I doubt that's a user.")
  File "/root/bot2/lib/python3.10/site-packages/telegram/message.py", line 977, in reply_text
    return self.bot.send_message(
  File "/root/bot2/lib/python3.10/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/telegram/bot.py", line 534, in send_message
    return self._message(  # type: ignore[return-value]
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/extbot.py", line 203, in _message
    result = super()._message(
  File "/root/bot2/lib/python3.10/site-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/root/bot2/lib/python3.10/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
  File "/root/bot2/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/root/bot2/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message to be replied not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 569, in process_update
    self.dispatch_error(update, exc)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] Unhandled exception on handler
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 867, in handler
    meme = await drawText(file, text)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 900, in drawText
    u_width, u_height = draw.textsize(u_text, font=m_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-25_01-00-00/db_LuffyRoxbot_2024-06-25_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff7413d7a00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot6535771079:AAGbb0GBOW_seJNRRY5jQKq3xt7iE_PM81U/getUpdates
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-26_01-00-00/db_LuffyRoxbot_2024-06-26_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 400, in _pooled
    self.dispatch_error(promise.update, promise.exception, promise=promise)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff740fffee0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot6535771079:AAGbb0GBOW_seJNRRY5jQKq3xt7iE_PM81U/getUpdates
[ᴇxᴏɴ] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff7847e43d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot6535771079:AAGbb0GBOW_seJNRRY5jQKq3xt7iE_PM81U/getUpdates
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-27_01-00-00/db_LuffyRoxbot_2024-06-27_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-28_01-00-00/db_LuffyRoxbot_2024-06-28_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] HTTP Request: GET https://api.weather.com/v3/location/search?apiKey=8de2d8b3a93542c9a2d8b3a935a2c909&format=json&language=en&query=Jodhpur "HTTP/2 200 OK"
[ᴇxᴏɴ] HTTP Request: GET https://api.weather.com/v3/aggcommon/v3-wx-observations-current?apiKey=8de2d8b3a93542c9a2d8b3a935a2c909&format=json&language=en&geocode=26.294%2C73.022&units=m "HTTP/2 200 OK"
[ᴇxᴏɴ] HTTP Request: GET https://api.weather.com/v3/location/search?apiKey=8de2d8b3a93542c9a2d8b3a935a2c909&format=json&language=en&query=Assam%20hojai "HTTP/2 200 OK"
[ᴇxᴏɴ] HTTP Request: GET https://api.weather.com/v3/aggcommon/v3-wx-observations-current?apiKey=8de2d8b3a93542c9a2d8b3a935a2c909&format=json&language=en&geocode=26.003%2C92.854&units=m "HTTP/2 200 OK"
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-29_01-00-00/db_LuffyRoxbot_2024-06-29_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-06-30_01-00-00/db_LuffyRoxbot_2024-06-30_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Kattegala%20gube%20naayi%20hydra%20marjao "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=kn&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Kattegala%20gube%20naayi%20hydra%20marjao "HTTP/1.1 200 OK"
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/root/ExonRobot/Exon/modules/helper_funcs/handlers.py", line 128, in handle_update
    return self.callback(update, context)
  File "/root/ExonRobot/Exon/modules/feds.py", line 236, in fed_chat
    if not is_user_admin(update.effective_chat, user_id):
  File "/root/ExonRobot/Exon/modules/helper_funcs/chat_status.py", line 79, in is_user_admin
    chat = update.effective_chat
AttributeError: 'Chat' object has no attribute 'effective_chat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 569, in process_update
    self.dispatch_error(update, exc)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 400, in _pooled
    self.dispatch_error(promise.update, promise.exception, promise=promise)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20Possible%20related%20search%3A%C2%A0%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%20%E3%83%88%E3%83%AA%E3%82%AC%E3%83%BC%20%E8%BF%85%20%E6%82%A0%E4%B8%80%20%E5%A3%81%E7%B4%99%0A2.%20%E3%80%8C%E8%BF%85%E6%82%A0%E4%B8%80%E3%80%8D%E3%81%AE%E3%82%A2%E3%82%A4%E3%83%87%E3%82%A2%2029%20%E4%BB%B6%20%7C%20%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%83%88%E3%83%AA%E3%82%AC%E3%83%BC%20%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%20...%0A3.%20%E8%BF%85%20%E6%82%A0%E4%B8%80%20%E5%A3%81%E7%B4%99%E3%81%AE%E7%94%BB%E5%83%8F5%E7%82%B9%EF%BD%9C%E5%AE%8C%E5%85%A8%E7%84%A1%E6%96%99%E7%94%BB%E5%83%8F%E6%A4%9C%E7%B4%A2%E3%81%AE%E3%83%97%E3%83%AA%E7%94%BB%E5%83%8F%20%20byGMO%0A4.%20Y%C5%ABichi%20Jin%20Wallpapers%20-%20Alpha%20Coders%0A5.%20Y%C5%ABichi%20Jin%20-%20Desktop%20Wallpapers%2C%20Phone%20...%20-%20Alpha%20Coders%0A6.%20World%20Trigger%20-%20Desktop%20Wallpapers%2C%20Phone%20...%20-%20Alpha%20Coders%0A7.%20Download%20Y%C5%ABma%20Kuga%20Anime%20World%20Trigger%204k%20Ultra%20HD%20...%0A8.%20Jin%20Yuuichi%20%28Jin%20Yuichi%29%2C%20World%20Trigger%20%7C%20page%203%20-%20Zerochan "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=ja&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20Possible%20related%20search%3A%C2%A0%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%20%E3%83%88%E3%83%AA%E3%82%AC%E3%83%BC%20%E8%BF%85%20%E6%82%A0%E4%B8%80%20%E5%A3%81%E7%B4%99%0A2.%20%E3%80%8C%E8%BF%85%E6%82%A0%E4%B8%80%E3%80%8D%E3%81%AE%E3%82%A2%E3%82%A4%E3%83%87%E3%82%A2%2029%20%E4%BB%B6%20%7C%20%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%83%88%E3%83%AA%E3%82%AC%E3%83%BC%20%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%20...%0A3.%20%E8%BF%85%20%E6%82%A0%E4%B8%80%20%E5%A3%81%E7%B4%99%E3%81%AE%E7%94%BB%E5%83%8F5%E7%82%B9%EF%BD%9C%E5%AE%8C%E5%85%A8%E7%84%A1%E6%96%99%E7%94%BB%E5%83%8F%E6%A4%9C%E7%B4%A2%E3%81%AE%E3%83%97%E3%83%AA%E7%94%BB%E5%83%8F%20%20byGMO%0A4.%20Y%C5%ABichi%20Jin%20Wallpapers%20-%20Alpha%20Coders%0A5.%20Y%C5%ABichi%20Jin%20-%20Desktop%20Wallpapers%2C%20Phone%20...%20-%20Alpha%20Coders%0A6.%20World%20Trigger%20-%20Desktop%20Wallpapers%2C%20Phone%20...%20-%20Alpha%20Coders%0A7.%20Download%20Y%C5%ABma%20Kuga%20Anime%20World%20Trigger%204k%20Ultra%20HD%20...%0A8.%20Jin%20Yuuichi%20%28Jin%20Yuichi%29%2C%20World%20Trigger%20%7C%20page%203%20-%20Zerochan "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20Possible%20related%20search%3A%C2%A0%D8%B5%D9%88%D8%B1%20%D8%A7%D9%86%D9%85%D9%8A%20%D9%85%D8%A7%D8%B4%0A2.%20Mash%20Vandead%20%7C%20Anime%2C%20Manga%2C%20Anime%20boy%20-%20Pinterest%0A3.%20Luxury%20fashion%20%26%20independent%20designers%20%7C%20SSENSE%20-%20Pinterest%0A4.%20Dottore%20%28iliapanchuk%29%20-%20Profile%20-%20Pinterest%0A5.%20Mashes%20Song%20Girl%20Singing%20%7C%20TikTok%0A6.%20Dottore%20%28iliapanchuk%29%20-%20Profile%20%7C%20Pinterest%0A7.%2012%20ide%20Rayne%20Ames%20di%202024%20-%20Pinterest "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20Possible%20related%20search%3A%C2%A0%D8%B5%D9%88%D8%B1%20%D8%A7%D9%86%D9%85%D9%8A%20%D9%85%D8%A7%D8%B4%0A2.%20Mash%20Vandead%20%7C%20Anime%2C%20Manga%2C%20Anime%20boy%20-%20Pinterest%0A3.%20Luxury%20fashion%20%26%20independent%20designers%20%7C%20SSENSE%20-%20Pinterest%0A4.%20Dottore%20%28iliapanchuk%29%20-%20Profile%20-%20Pinterest%0A5.%20Mashes%20Song%20Girl%20Singing%20%7C%20TikTok%0A6.%20Dottore%20%28iliapanchuk%29%20-%20Profile%20%7C%20Pinterest%0A7.%2012%20ide%20Rayne%20Ames%20di%202024%20-%20Pinterest "HTTP/1.1 200 OK"
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-07-01_01-00-00/db_LuffyRoxbot_2024-07-01_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/bot2/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 400, in _pooled
    self.dispatch_error(promise.update, promise.exception, promise=promise)
  File "/root/bot2/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 813, in dispatch_error
    callback(update, context)
  File "/root/ExonRobot/Exon/modules/error_handling.py", line 104, in error_callback
    response = response.json()
  File "/root/bot2/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ᴇxᴏɴ] Error while getting Updates: Bad Gateway
[ᴇxᴏɴ] Error while getting Updates: Bad Gateway
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20%E3%80%8C%E3%81%B0%E3%81%B6%E6%A3%98%E3%81%8F%E3%82%93%E3%81%A8%E7%9B%AE%E6%BD%B0%E3%81%97%E3%81%95%E3%82%8C%E3%81%A6%E3%82%8B%E3%83%91%E3%83%B3%E3%83%80%20%E3%80%8D%7C%E3%81%9F%E3%81%BE%E3%82%89%E3%8C%A0%E3%81%AE%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%0A2.%201%20result%0A3.%20See%20exact%20matches%0A4.%20Kiyoshimo%20%28Kantai%20Collection%29%20Image%20by%2038%20colis%20%232718005%20-%20Zerochan%20Anime%20Image%20Board%0A5.%20AI%20Art%3A%20%F0%9F%90%BC%20by%20%40%E3%82%86%E3%81%8D%E3%81%AA%E3%81%93%20%7C%20PixAI%0A6.%20Qin%20Liangyu%20%5BFGO%5D%20%3A%20r%2FAnimeHoodies%0A7.%20inumaki%20toge%20and%20panda%20%28jujutsu%20kaisen%29%20drawn%20by%20stray0641071225%20%7C%20Danbooru%0A8.%20%F0%93%86%A9%E2%98%85%F0%93%86%AA%20on%20Instagram%3A%20%5C%0A9.%20Pinterest%20-%20%E3%83%94%E3%83%B3%E3%82%BF%E3%83%AC%E3%82%B9%E3%83%88%0A10.%20NyJaun%20Parker%20%28nyjaunp%29%20-%20Profile%20%7C%20Pinterest%0A%0AMore%20Results "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=ja&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20%E3%80%8C%E3%81%B0%E3%81%B6%E6%A3%98%E3%81%8F%E3%82%93%E3%81%A8%E7%9B%AE%E6%BD%B0%E3%81%97%E3%81%95%E3%82%8C%E3%81%A6%E3%82%8B%E3%83%91%E3%83%B3%E3%83%80%20%E3%80%8D%7C%E3%81%9F%E3%81%BE%E3%82%89%E3%8C%A0%E3%81%AE%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%0A2.%201%20result%0A3.%20See%20exact%20matches%0A4.%20Kiyoshimo%20%28Kantai%20Collection%29%20Image%20by%2038%20colis%20%232718005%20-%20Zerochan%20Anime%20Image%20Board%0A5.%20AI%20Art%3A%20%F0%9F%90%BC%20by%20%40%E3%82%86%E3%81%8D%E3%81%AA%E3%81%93%20%7C%20PixAI%0A6.%20Qin%20Liangyu%20%5BFGO%5D%20%3A%20r%2FAnimeHoodies%0A7.%20inumaki%20toge%20and%20panda%20%28jujutsu%20kaisen%29%20drawn%20by%20stray0641071225%20%7C%20Danbooru%0A8.%20%F0%93%86%A9%E2%98%85%F0%93%86%AA%20on%20Instagram%3A%20%5C%0A9.%20Pinterest%20-%20%E3%83%94%E3%83%B3%E3%82%BF%E3%83%AC%E3%82%B9%E3%83%88%0A10.%20NyJaun%20Parker%20%28nyjaunp%29%20-%20Profile%20%7C%20Pinterest%0A%0AMore%20Results "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20%E3%80%90%E9%96%92%E8%81%8A%E3%80%91%E5%B0%B1%E6%84%9B%E9%AD%94%E5%8B%87%E9%85%8D~%E6%89%80%E4%BB%A5%E6%94%B6%E8%97%8F%E4%B8%80%E4%BA%9B%E5%9C%96%20%28%E8%8B%A5%E7%B5%90%E5%B1%80%E7%9C%9F%E6%98%AF%E6%9C%80%E5%BE%8C%E9%82%A3%E5%BC%B5%E5%9C%96.%E6%9C%AC%E4%BA%BA%E5%B0%B1%E6%95%97%E4%B8%80%E5%A5%97%21%21%21%29%20%40%E5%92%8C%E3%83%B6%E5%8E%9F%E8%81%A1%E5%8F%B8%20%E4%BD%9C%E5%93%81%E9%9B%86%EF%BC%88%E6%89%93%E5%B7%A5%E5%90%A7%EF%BC%81%E9%AD%94%E7%8E%8B%E5%A4%A7%E4%BA%BA%EF%BC%89%20%E5%93%88%E5%95%A6%E6%9D%BF%20-%20%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9%0A2.%2010%2011%20%E2%80%93%20Artofit%0A3.%20%D0%9A%D0%BD%D1%8F%D0%B7%D1%8C%20%D1%82%D1%8C%D0%BC%D1%8B%20%D0%B8%20%D0%B3%D0%B5%D1%80%D0%BE%D0%B9%20-%20%D1%84%D0%BE%D1%82%D0%BE%20%D0%B8%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8%3A%2062%20%D1%88%D1%82%D1%83%D0%BA%0A4.%203%20results%0A5.%20See%20exact%20matches%0A6.%20The%20Devil%20is%20a%20Part-Timer%21%0A7.%20nilitsu%20shokei%20shoujo%20no%20virgin%20road%20menou%20%28shokei%20shoujo%29%20%7C%20%23668200%20%7C%20yande.re%0A8.%20%2F%20%7C%20yande.re%0A9.%20BunCho%20%E2%80%93%20A%20Scenario%20Creation%20Support%20AI%20to%20Assist%20in%20Game%20and%20Novel%20Creation%20%28Part%202%29%20%7C%20InnoUvators%0A10.%20Micaiah%20-%20Fire%20Emblem%3A%20Path%20of%20Radiance%20-%20Image%20by%20Kyulog%20%232584410%20-%20Zerochan%20Anime%20Image%20Board%0A%0AMore%20Results "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=1.%20%E3%80%90%E9%96%92%E8%81%8A%E3%80%91%E5%B0%B1%E6%84%9B%E9%AD%94%E5%8B%87%E9%85%8D~%E6%89%80%E4%BB%A5%E6%94%B6%E8%97%8F%E4%B8%80%E4%BA%9B%E5%9C%96%20%28%E8%8B%A5%E7%B5%90%E5%B1%80%E7%9C%9F%E6%98%AF%E6%9C%80%E5%BE%8C%E9%82%A3%E5%BC%B5%E5%9C%96.%E6%9C%AC%E4%BA%BA%E5%B0%B1%E6%95%97%E4%B8%80%E5%A5%97%21%21%21%29%20%40%E5%92%8C%E3%83%B6%E5%8E%9F%E8%81%A1%E5%8F%B8%20%E4%BD%9C%E5%93%81%E9%9B%86%EF%BC%88%E6%89%93%E5%B7%A5%E5%90%A7%EF%BC%81%E9%AD%94%E7%8E%8B%E5%A4%A7%E4%BA%BA%EF%BC%89%20%E5%93%88%E5%95%A6%E6%9D%BF%20-%20%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9%0A2.%2010%2011%20%E2%80%93%20Artofit%0A3.%20%D0%9A%D0%BD%D1%8F%D0%B7%D1%8C%20%D1%82%D1%8C%D0%BC%D1%8B%20%D0%B8%20%D0%B3%D0%B5%D1%80%D0%BE%D0%B9%20-%20%D1%84%D0%BE%D1%82%D0%BE%20%D0%B8%20%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8%3A%2062%20%D1%88%D1%82%D1%83%D0%BA%0A4.%203%20results%0A5.%20See%20exact%20matches%0A6.%20The%20Devil%20is%20a%20Part-Timer%21%0A7.%20nilitsu%20shokei%20shoujo%20no%20virgin%20road%20menou%20%28shokei%20shoujo%29%20%7C%20%23668200%20%7C%20yande.re%0A8.%20%2F%20%7C%20yande.re%0A9.%20BunCho%20%E2%80%93%20A%20Scenario%20Creation%20Support%20AI%20to%20Assist%20in%20Game%20and%20Novel%20Creation%20%28Part%202%29%20%7C%20InnoUvators%0A10.%20Micaiah%20-%20Fire%20Emblem%3A%20Path%20of%20Radiance%20-%20Image%20by%20Kyulog%20%232584410%20-%20Zerochan%20Anime%20Image%20Board%0A%0AMore%20Results "HTTP/1.1 200 OK"
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-07-02_01-00-00/db_LuffyRoxbot_2024-07-02_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Kaizoku%20ni%20Moye%20Moye "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=ja&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Kaizoku%20ni%20Moye%20Moye "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Anatawa%20sarudesu "HTTP/1.1 200 OK"
[ᴇxᴏɴ] HTTP Request: POST https://translate.google.com/translate_a/single?client=gtx&sl=ja&tl=en&dt=t&ie=utf-8&oe=utf-8&dj=1&q=Anatawa%20sarudesu "HTTP/1.1 200 OK"
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.01849368222287545>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.01849368222287545>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.01849368222287545>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.01849368222287545>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.018473310573933022>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.018473310573933022>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.018473310573933022>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.018473310573933022>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] {"message": "Waiting for suitable server to become available", "selector": "<function writable_server_selector at 0x7ff7cfa85fc0>", "operation": "update", "topologyDescription": "<TopologyDescription id: 66781c4c4692490b22d69d82, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qk6fva9-shard-00-00.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-00.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-01.nnssges.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-qk6fva9-shard-00-01.nnssges.mongodb.net:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qk6fva9-shard-00-02.nnssges.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.018473310573933022>]>", "clientId": {"$oid": "66781c4c4692490b22d69d82"}, "remainingTimeMS": 29}
[ᴇxᴏɴ] Unhandled exception on handler
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 867, in handler
    meme = await drawText(file, text)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 900, in drawText
    u_width, u_height = draw.textsize(u_text, font=m_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
[ᴇxᴏɴ] Unhandled exception on handler
Traceback (most recent call last):
  File "/root/bot2/lib/python3.10/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 867, in handler
    meme = await drawText(file, text)
  File "/root/ExonRobot/Exon/modules/stickers.py", line 900, in drawText
    u_width, u_height = draw.textsize(u_text, font=m_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
[ᴇxᴏɴ] Performing db backup
[ᴇxᴏɴ] error while running db backup
[ᴇxᴏɴ] /bin/sh: 1: pg_dump: not found

[ᴇxᴏɴ] Copying config, and logs to backup location
[ᴇxᴏɴ] Zipping the backup
[ᴇxᴏɴ] Zip initiated
[ᴇxᴏɴ] zipping db backup successful!
[ᴇxᴏɴ]   adding: backups/2024-07-03_01-00-00/db_LuffyRoxbot_2024-07-03_01-00-00.tar (stored 0%)

[ᴇxᴏɴ] Zip done
[ᴇxᴏɴ] Removing zipped files
[ᴇxᴏɴ] Backup done
[ᴇxᴏɴ] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff7965b6290>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot6535771079:AAGbb0GBOW_seJNRRY5jQKq3xt7iE_PM81U/getChatMember
